# Generated by Django 5.0.6 on 2024-06-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Normativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreto', models.CharField(max_length=150, verbose_name='Decreto')),
                ('detalles', models.CharField(max_length=500, verbose_name='Detalles')),
                ('producto', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'Normativa',
                'verbose_name_plural': 'Normativas',
                'db_table': 'Normativa',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=True)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('producto', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Registro_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
                ('venta', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
            options={
                'verbose_name': 'Registro_venta',
                'verbose_name_plural': 'Registro_ventas',
                'db_table': 'Registro Venta',
            },
        ),
    ]
