# Generated by Django 5.0.6 on 2024-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_normativa_venta_registro_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
