# Generated by Django 5.0.6 on 2024-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_total',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
