# Generated by Django 5.0.6 on 2024-06-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_compra_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precio_total',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=9),
        ),
    ]
